# Site settings
title: "KIM JONG HEE"
encoding: UTF-8
email: bethjkim0311@gmail.com
url: https://spacekay.github.io/
description: "웹 개발자로서의 새로운 세계로 한 발짝을 내딛는, 모험가 김종희입니다."
keywords: "김종희,spacekay,kimjonghee,backend,java,python,javascript,springboot,django"
skills: "1994. 3. 11. ~ challenging<br>Imaginative, Risk-taking, Pursuing Self-improvement"
meta_author: Kim Jonghee

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: spacekay

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1898bc
  primary-rgb: "24, 152, 188"
  secondary: 2c3e50
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: 김종희 KIM JONGHEE
  location: Location
  social: Around the Web
  credits: Credit

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: pencil
    url: http://thespacekay.tistory.com
  - title: github
    url: http://github.com/spacekay

# Postal address (add as many lines as necessary)
address:
  - line: 서울 관악구 남현2길 59
  - line: bethjkim0311@gmail.com

# Credits content
credits: 'This page is powered by<br>Freelancer theme by Bootstrap'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
